name: app_nasz_gpt
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - pip:
    - openai==1.98.0
    - langfuse==2.40.0
    - streamlit==1.24.0
    - python-dotenv==1.1.1
    - PyPDF2==3.0.1
    - python-docx==1.1.0
    - requests==2.31.0

